project_id = "bcokciysbyuaeodnsxas"

[functions.save-result]
verify_jwt = false

[functions.get-result]
verify_jwt = false

[functions.import-legacy-csv]
verify_jwt = false

[functions.send-legacy-notification]
verify_jwt = false

[functions.get-country-stats]
verify_jwt = false

[functions.get-comments]
verify_jwt = false
